tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#bec6e0",
        tertiary: "#000000",
        "on-secondary-fixed": "#0b1c30",
        "tertiary-fixed-dim": "#4edea3",
        "on-primary": "#ffffff",
        "inverse-surface": "#2d3133",
        "secondary-fixed-dim": "#b7c8e1",
        "on-tertiary-fixed": "#002113",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        primary: "#000000",
        "error-container": "#ffdad6",
        "surface-dim": "#d8dadc",
        "tertiary-container": "#002113",
        "on-tertiary-fixed-variant": "#005236",
        "on-surface-variant": "#45464d",
        "on-surface": "#191c1e",
        "primary-container": "#131b2e",
        "on-secondary-fixed-variant": "#38485d",
        "surface-tint": "#565e74",
        secondary: "#505f76",
        "on-primary-fixed": "#131b2e",
        "inverse-on-surface": "#eff1f3",
        "surface-bright": "#f7f9fb",
        "surface-container": "#eceef0",
        "primary-fixed": "#dae2fd",
        "surface-variant": "#e0e3e5",
        "on-secondary-container": "#54647a",
        background: "#f7f9fb",
        "on-background": "#191c1e",
        surface: "#f7f9fb",
        "surface-container-highest": "#e0e3e5",
        "on-error-container": "#93000a",
        "inverse-primary": "#bec6e0",
        "on-secondary": "#ffffff",
        "on-primary-container": "#7c839b",
        "secondary-container": "#d0e1fb",
        "secondary-fixed": "#d3e4fe",
        "outline-variant": "#c6c6cd",
        outline: "#76777d",
        "on-error": "#ffffff",
        "surface-container-high": "#e6e8ea",
        "surface-container-low": "#f2f4f6",
        "on-tertiary-container": "#009668",
        "tertiary-fixed": "#6ffbbe",
        error: "#ba1a1a",
        "on-primary-fixed-variant": "#3f465c",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        md: "16px",
        lg: "24px",
        xs: "4px",
        xl: "32px",
        base: "4px",
        sm: "8px",
        "sidebar-width": "280px",
        "container-max": "1440px",
      },
      fontFamily: {
        "headline-lg": ["Inter"],
        "body-lg": ["Inter"],
        "headline-sm": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "body-sm": ["Inter"],
        "label-md": ["Inter"],
        "headline-md": ["Inter"],
        "body-md": ["Inter"],
      },
      fontSize: {
        "headline-lg": [
          "32px",
          {
            lineHeight: "40px",
            letterSpacing: "-0.02em",
            fontWeight: "700",
          },
        ],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-sm": [
          "20px",
          { lineHeight: "28px", fontWeight: "600" },
        ],
        "headline-lg-mobile": [
          "24px",
          { lineHeight: "32px", fontWeight: "700" },
        ],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "label-md": [
          "12px",
          {
            lineHeight: "16px",
            letterSpacing: "0.05em",
            fontWeight: "600",
          },
        ],
        "headline-md": [
          "24px",
          { lineHeight: "32px", fontWeight: "600" },
        ],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
      },
    },
  },
};